apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: torpili
  name: mr-manager-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "update", "patch", "watch", "delete", "deletecollection"]

# for request verbs, https://kubernetes.io/docs/reference/access-authn-authz/authorization/#request-verb-resource
