version: '3.7'

services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=local_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    hostname: db

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    container_name: web
    build: .
    ports:
      - "80:80"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB=local_db
      - SECRET_KEY=supersecretkey
    depends_on:
      db:
        condition: service_healthy
        restart: true
