FROM python:3.12-slim
LABEL authors="christofilojohn"

#ENTRYPOINT ["top", "-b"]
# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file into the container
#COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the working directory contents into the container
COPY . .

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "./app.py"]