apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
  namespace: torpili
spec:
  serviceName: test-service
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      volumes:
        - name: test
          persistentVolumeClaim:
            claimName: test-shared-pvc
      containers:
        - name: test-container
          image: alpine
          command: ["/bin/sh"]
          args:
            - -c 
            - |
              export POD_INDEX=$(echo $POD_NAME | awk -F'-' '{print $NF}')
              export POD_INDEX=${POD_INDEX}
              echo "Pod index is $POD_INDEX" > test$POD_INDEX
              sleep 3600
          volumeMounts:
          - mountPath: "/mnt/longhorn"
            name: test
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 216Mi
              cpu: "0.2"
          ports:
            - containerPort: 5432
  volumeClaimTemplates:
    - metadata:
        name: podspecific-volume
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: longhorn
        resources:
          requests:
            storage: 0.25Gi
