apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    # no matchLabels because services are simpler (but allow for less config)
    app: test  # matches the selector tag of the deployments pods
  type: ClusterIP # ClusterIP only accessible from inside cluster (also has loadbalancing but it is handled by kubernetes exclusively (no aws loadbalancer for excample)), NodePort is reachable but uses node's IP so it changes

# reminder:
#   minikube service <service_name>
# to run it