apiVersion: v1
kind: Pod
metadata:
  name: mapper
  namespace: torpili
spec:
  containers:
  - name: mapper
    env:
      - name: POD_NAME
        value: pod-0
    image: georgestav/mapper:latest
    command: ["python", "mapper.py"] 
    args:
    - "/mnt/longhorn/split0.txt"
    volumeMounts:
    - mountPath: "/mnt/longhorn"
      name: longhorn-storage
  volumes:
  - name: longhorn-storage
    persistentVolumeClaim:
      claimName: longhorn-pvc
  restartPolicy: OnFailure
