apiVersion: v1
kind: Pod
metadata:
  name: reducer
  namespace: torpili
spec:
  containers:
  - name: reducer
    env:
      - name: POD_NAME
        value: pod-0
    image: georgestav/reducer:latest
    command: ["python", "reducer.py"] 
    volumeMounts:
    - mountPath: "/mnt/longhorn"
      name: longhorn-storage
  volumes:
  - name: longhorn-storage
    persistentVolumeClaim:
      claimName: longhorn-pvc
  restartPolicy: OnFailure
