apiVersion: v1
kind: Pod
metadata:
  name: splitter
  namespace: torpili
spec:
  containers:
  - name: splitter
    image: georgestav/splitter:latest
    command: ["python", "splitter.py"] 
    args: 
    - "/mnt/longhorn/input_file"
    - "3"
    volumeMounts:
    - mountPath: "/mnt/longhorn"
      name: longhorn-storage
  volumes:
  - name: longhorn-storage
    persistentVolumeClaim:
      claimName: longhorn-pvc
  restartPolicy: OnFailure