apiVersion: v1
kind: Pod
metadata:
  name: longhorn-read-pod
  namespace: torpili
spec:
  containers:
  - name: longhorn-reader
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
    - mountPath: "/mnt/longhorn"
      name: longhorn-storage
  volumes:
  - name: longhorn-storage
    persistentVolumeClaim:
      claimName: longhorn-pvc
