apiVersion: v1
kind: Pod
metadata:
  name: longhorn-write-pod
  namespace: torpili
spec:
  containers:
  - name: longhorn-writer
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "echo 'Hello, testing!' > /mnt/longhorn/hello.txt && chmod 666 /mnt/longhorn/hello.txt && sleep 3600"]
    volumeMounts:
    - mountPath: "/mnt/longhorn"
      name: longhorn-storage
  volumes:
  - name: longhorn-storage
    persistentVolumeClaim:
      claimName: longhorn-pvc